//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at https://docs.xperience.io/.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using CMS.DocumentEngine;
using CMS.DocumentEngine.Types.Aiminfomatics;

[assembly: RegisterDocumentType(HireDeveloper.CLASS_NAME, typeof(HireDeveloper))]

namespace CMS.DocumentEngine.Types.Aiminfomatics
{
	/// <summary>
	/// Represents a content item of type HireDeveloper.
	/// </summary>
	public partial class HireDeveloper : TreeNode
	{
		#region "Constants and variables"

		/// <summary>
		/// The name of the data class.
		/// </summary>
		public const string CLASS_NAME = "Aiminfomatics.HireDeveloper";


		/// <summary>
		/// The instance of the class that provides extended API for working with HireDeveloper fields.
		/// </summary>
		private readonly HireDeveloperFields mFields;

		#endregion


		#region "Properties"

		/// <summary>
		/// HireADeveloperID.
		/// </summary>
		[DatabaseIDField]
		public int HireADeveloperID
		{
			get
			{
				return ValidationHelper.GetInteger(GetValue("HireADeveloperID"), 0);
			}
			set
			{
				SetValue("HireADeveloperID", value);
			}
		}


		/// <summary>
		/// Services.
		/// </summary>
		[DatabaseField]
		public string Services
		{
			get
			{
				return ValidationHelper.GetString(GetValue("Services"), @"");
			}
			set
			{
				SetValue("Services", value);
			}
		}


		/// <summary>
		/// Satisfaction.
		/// </summary>
		[DatabaseField]
		public string Satisfaction
		{
			get
			{
				return ValidationHelper.GetString(GetValue("Satisfaction"), @"");
			}
			set
			{
				SetValue("Satisfaction", value);
			}
		}


		/// <summary>
		/// Mobile Application.
		/// </summary>
		[DatabaseField]
		public string MobileApplication
		{
			get
			{
				return ValidationHelper.GetString(GetValue("MobileApplication"), @"");
			}
			set
			{
				SetValue("MobileApplication", value);
			}
		}


		/// <summary>
		/// Web Design Dev.
		/// </summary>
		[DatabaseField]
		public string WebDesignDev
		{
			get
			{
				return ValidationHelper.GetString(GetValue("WebDesignDev"), @"");
			}
			set
			{
				SetValue("WebDesignDev", value);
			}
		}


		/// <summary>
		/// Internet Marketing.
		/// </summary>
		[DatabaseField]
		public string InternetMarketing
		{
			get
			{
				return ValidationHelper.GetString(GetValue("InternetMarketing"), @"");
			}
			set
			{
				SetValue("InternetMarketing", value);
			}
		}


		/// <summary>
		/// E Commerce Solutions.
		/// </summary>
		[DatabaseField]
		public string ECommerceSol
		{
			get
			{
				return ValidationHelper.GetString(GetValue("ECommerceSol"), @"");
			}
			set
			{
				SetValue("ECommerceSol", value);
			}
		}


		/// <summary>
		/// Hire A developer.
		/// </summary>
		[DatabaseField]
		public string HireAdeveloper
		{
			get
			{
				return ValidationHelper.GetString(GetValue("HireAdeveloper"), @"");
			}
			set
			{
				SetValue("HireAdeveloper", value);
			}
		}


		/// <summary>
		/// Hire Professional.
		/// </summary>
		[DatabaseField]
		public string HireProfessionalDev
		{
			get
			{
				return ValidationHelper.GetString(GetValue("HireProfessionalDev"), @"");
			}
			set
			{
				SetValue("HireProfessionalDev", value);
			}
		}


		/// <summary>
		/// Hire Professionals Txt.
		/// </summary>
		[DatabaseField]
		public string HireProfessionalsTxt
		{
			get
			{
				return ValidationHelper.GetString(GetValue("HireProfessionalsTxt"), @"");
			}
			set
			{
				SetValue("HireProfessionalsTxt", value);
			}
		}


		/// <summary>
		/// Gets an object that provides extended API for working with HireDeveloper fields.
		/// </summary>
		[RegisterProperty]
		public HireDeveloperFields Fields
		{
			get
			{
				return mFields;
			}
		}


		/// <summary>
		/// Provides extended API for working with HireDeveloper fields.
		/// </summary>
		[RegisterAllProperties]
		public partial class HireDeveloperFields : AbstractHierarchicalObject<HireDeveloperFields>
		{
			/// <summary>
			/// The content item of type HireDeveloper that is a target of the extended API.
			/// </summary>
			private readonly HireDeveloper mInstance;


			/// <summary>
			/// Initializes a new instance of the <see cref="HireDeveloperFields" /> class with the specified content item of type HireDeveloper.
			/// </summary>
			/// <param name="instance">The content item of type HireDeveloper that is a target of the extended API.</param>
			public HireDeveloperFields(HireDeveloper instance)
			{
				mInstance = instance;
			}


			/// <summary>
			/// HireADeveloperID.
			/// </summary>
			public int HireADeveloperID
			{
				get
				{
					return mInstance.HireADeveloperID;
				}
				set
				{
					mInstance.HireADeveloperID = value;
				}
			}


			/// <summary>
			/// Services.
			/// </summary>
			public string Services
			{
				get
				{
					return mInstance.Services;
				}
				set
				{
					mInstance.Services = value;
				}
			}


			/// <summary>
			/// Satisfaction.
			/// </summary>
			public string Satisfaction
			{
				get
				{
					return mInstance.Satisfaction;
				}
				set
				{
					mInstance.Satisfaction = value;
				}
			}


			/// <summary>
			/// Mobile Application.
			/// </summary>
			public string MobileApplication
			{
				get
				{
					return mInstance.MobileApplication;
				}
				set
				{
					mInstance.MobileApplication = value;
				}
			}


			/// <summary>
			/// Web Design Dev.
			/// </summary>
			public string WebDesignDev
			{
				get
				{
					return mInstance.WebDesignDev;
				}
				set
				{
					mInstance.WebDesignDev = value;
				}
			}


			/// <summary>
			/// Internet Marketing.
			/// </summary>
			public string InternetMarketing
			{
				get
				{
					return mInstance.InternetMarketing;
				}
				set
				{
					mInstance.InternetMarketing = value;
				}
			}


			/// <summary>
			/// E Commerce Solutions.
			/// </summary>
			public string ECommerceSol
			{
				get
				{
					return mInstance.ECommerceSol;
				}
				set
				{
					mInstance.ECommerceSol = value;
				}
			}


			/// <summary>
			/// Hire A developer.
			/// </summary>
			public string HireAdeveloper
			{
				get
				{
					return mInstance.HireAdeveloper;
				}
				set
				{
					mInstance.HireAdeveloper = value;
				}
			}


			/// <summary>
			/// Hire Professional.
			/// </summary>
			public string HireProfessionalDev
			{
				get
				{
					return mInstance.HireProfessionalDev;
				}
				set
				{
					mInstance.HireProfessionalDev = value;
				}
			}


			/// <summary>
			/// Hire Professionals Txt.
			/// </summary>
			public string HireProfessionalsTxt
			{
				get
				{
					return mInstance.HireProfessionalsTxt;
				}
				set
				{
					mInstance.HireProfessionalsTxt = value;
				}
			}
		}

		#endregion


		#region "Constructors"

		/// <summary>
		/// Initializes a new instance of the <see cref="HireDeveloper" /> class.
		/// </summary>
		public HireDeveloper() : base(CLASS_NAME)
		{
			mFields = new HireDeveloperFields(this);
		}

		#endregion
	}
}