//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at https://docs.xperience.io/.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using CMS.DocumentEngine;
using CMS.DocumentEngine.Types.Aiminfomatics;

[assembly: RegisterDocumentType(Services.CLASS_NAME, typeof(Services))]

namespace CMS.DocumentEngine.Types.Aiminfomatics
{
	/// <summary>
	/// Represents a content item of type Services.
	/// </summary>
	public partial class Services : TreeNode
	{
		#region "Constants and variables"

		/// <summary>
		/// The name of the data class.
		/// </summary>
		public const string CLASS_NAME = "Aiminfomatics.Services";


		/// <summary>
		/// The instance of the class that provides extended API for working with Services fields.
		/// </summary>
		private readonly ServicesFields mFields;

		#endregion


		#region "Properties"

		/// <summary>
		/// ServicesID.
		/// </summary>
		[DatabaseIDField]
		public int ServicesID
		{
			get
			{
				return ValidationHelper.GetInteger(GetValue("ServicesID"), 0);
			}
			set
			{
				SetValue("ServicesID", value);
			}
		}


		/// <summary>
		/// Services.
		/// </summary>
		[DatabaseField]
		public string Services1
		{
			get
			{
				return ValidationHelper.GetString(GetValue("Services"), @"");
			}
			set
			{
				SetValue("Services", value);
			}
		}


		/// <summary>
		/// Satisfaction.
		/// </summary>
		[DatabaseField]
		public string ServicesSatisfaction
		{
			get
			{
				return ValidationHelper.GetString(GetValue("ServicesSatisfaction"), @"");
			}
			set
			{
				SetValue("ServicesSatisfaction", value);
			}
		}


		/// <summary>
		/// Our services.
		/// </summary>
		[DatabaseField]
		public string OurServices
		{
			get
			{
				return ValidationHelper.GetString(GetValue("OurServices"), @"");
			}
			set
			{
				SetValue("OurServices", value);
			}
		}


		/// <summary>
		/// Mobile Application.
		/// </summary>
		[DatabaseField]
		public string MobileApplication
		{
			get
			{
				return ValidationHelper.GetString(GetValue("MobileApplication"), @"");
			}
			set
			{
				SetValue("MobileApplication", value);
			}
		}


		/// <summary>
		/// Mobile Application Img.
		/// </summary>
		[DatabaseField]
		public Guid MobileApplicationImg
		{
			get
			{
				return ValidationHelper.GetGuid(GetValue("MobileApplicationImg"), Guid.Empty);
			}
			set
			{
				SetValue("MobileApplicationImg", value);
			}
		}


		/// <summary>
		/// Web Design Development.
		/// </summary>
		[DatabaseField]
		public string WebDesignDevelopment
		{
			get
			{
				return ValidationHelper.GetString(GetValue("WebDesignDevelopment"), @"");
			}
			set
			{
				SetValue("WebDesignDevelopment", value);
			}
		}


		/// <summary>
		/// Web Design Img.
		/// </summary>
		[DatabaseField]
		public Guid WebDesignImg
		{
			get
			{
				return ValidationHelper.GetGuid(GetValue("WebDesignImg"), Guid.Empty);
			}
			set
			{
				SetValue("WebDesignImg", value);
			}
		}


		/// <summary>
		/// Internet Marketin.
		/// </summary>
		[DatabaseField]
		public string InternetMarketin
		{
			get
			{
				return ValidationHelper.GetString(GetValue("InternetMarketin"), @"");
			}
			set
			{
				SetValue("InternetMarketin", value);
			}
		}


		/// <summary>
		/// Seo Img.
		/// </summary>
		[DatabaseField]
		public Guid SeoImg
		{
			get
			{
				return ValidationHelper.GetGuid(GetValue("SeoImg"), Guid.Empty);
			}
			set
			{
				SetValue("SeoImg", value);
			}
		}


		/// <summary>
		/// E Commerce Solutions.
		/// </summary>
		[DatabaseField]
		public string ECommerceSolutions
		{
			get
			{
				return ValidationHelper.GetString(GetValue("ECommerceSolutions"), @"");
			}
			set
			{
				SetValue("ECommerceSolutions", value);
			}
		}


		/// <summary>
		/// Ecom Img.
		/// </summary>
		[DatabaseField]
		public Guid EcomImg
		{
			get
			{
				return ValidationHelper.GetGuid(GetValue("EcomImg"), Guid.Empty);
			}
			set
			{
				SetValue("EcomImg", value);
			}
		}


		/// <summary>
		/// Software Development.
		/// </summary>
		[DatabaseField]
		public string SoftwareDevelopment
		{
			get
			{
				return ValidationHelper.GetString(GetValue("SoftwareDevelopment"), @"");
			}
			set
			{
				SetValue("SoftwareDevelopment", value);
			}
		}


		/// <summary>
		/// Software Img.
		/// </summary>
		[DatabaseField]
		public Guid SoftwareImg
		{
			get
			{
				return ValidationHelper.GetGuid(GetValue("SoftwareImg"), Guid.Empty);
			}
			set
			{
				SetValue("SoftwareImg", value);
			}
		}


		/// <summary>
		/// Hire Developer.
		/// </summary>
		[DatabaseField]
		public string HireDeveloper
		{
			get
			{
				return ValidationHelper.GetString(GetValue("HireDeveloper"), @"");
			}
			set
			{
				SetValue("HireDeveloper", value);
			}
		}


		/// <summary>
		/// Hire Img.
		/// </summary>
		[DatabaseField]
		public Guid HireImg
		{
			get
			{
				return ValidationHelper.GetGuid(GetValue("HireImg"), Guid.Empty);
			}
			set
			{
				SetValue("HireImg", value);
			}
		}


		/// <summary>
		/// Gets an object that provides extended API for working with Services fields.
		/// </summary>
		[RegisterProperty]
		public ServicesFields Fields
		{
			get
			{
				return mFields;
			}
		}


		/// <summary>
		/// Provides extended API for working with Services fields.
		/// </summary>
		[RegisterAllProperties]
		public partial class ServicesFields : AbstractHierarchicalObject<ServicesFields>
		{
			/// <summary>
			/// The content item of type Services that is a target of the extended API.
			/// </summary>
			private readonly Services mInstance;


			/// <summary>
			/// Initializes a new instance of the <see cref="ServicesFields" /> class with the specified content item of type Services.
			/// </summary>
			/// <param name="instance">The content item of type Services that is a target of the extended API.</param>
			public ServicesFields(Services instance)
			{
				mInstance = instance;
			}


			/// <summary>
			/// ServicesID.
			/// </summary>
			public int ID
			{
				get
				{
					return mInstance.ServicesID;
				}
				set
				{
					mInstance.ServicesID = value;
				}
			}


			/// <summary>
			/// ServicesRelatedPage.
			/// </summary>
			public IEnumerable<TreeNode> RelatedPage
			{
				get
				{
					return mInstance.GetRelatedDocuments("ServicesRelatedPage");
				}
			}


			/// <summary>
			/// Services.
			/// </summary>
			public string Services
			{
				get
				{
					return mInstance.Services1;
				}
				set
				{
					mInstance.Services1 = value;
				}
			}


			/// <summary>
			/// Satisfaction.
			/// </summary>
			public string Satisfaction
			{
				get
				{
					return mInstance.ServicesSatisfaction;
				}
				set
				{
					mInstance.ServicesSatisfaction = value;
				}
			}


			/// <summary>
			/// Our services.
			/// </summary>
			public string OurServices
			{
				get
				{
					return mInstance.OurServices;
				}
				set
				{
					mInstance.OurServices = value;
				}
			}


			/// <summary>
			/// Mobile Application.
			/// </summary>
			public string MobileApplication
			{
				get
				{
					return mInstance.MobileApplication;
				}
				set
				{
					mInstance.MobileApplication = value;
				}
			}


			/// <summary>
			/// Mobile Application Img.
			/// </summary>
			public DocumentAttachment MobileApplicationImg
			{
				get
				{
					return mInstance.GetFieldDocumentAttachment("MobileApplicationImg");
				}
			}


			/// <summary>
			/// Web Design Development.
			/// </summary>
			public string WebDesignDevelopment
			{
				get
				{
					return mInstance.WebDesignDevelopment;
				}
				set
				{
					mInstance.WebDesignDevelopment = value;
				}
			}


			/// <summary>
			/// Web Design Img.
			/// </summary>
			public DocumentAttachment WebDesignImg
			{
				get
				{
					return mInstance.GetFieldDocumentAttachment("WebDesignImg");
				}
			}


			/// <summary>
			/// Internet Marketin.
			/// </summary>
			public string InternetMarketin
			{
				get
				{
					return mInstance.InternetMarketin;
				}
				set
				{
					mInstance.InternetMarketin = value;
				}
			}


			/// <summary>
			/// Seo Img.
			/// </summary>
			public DocumentAttachment SeoImg
			{
				get
				{
					return mInstance.GetFieldDocumentAttachment("SeoImg");
				}
			}


			/// <summary>
			/// E Commerce Solutions.
			/// </summary>
			public string ECommerceSolutions
			{
				get
				{
					return mInstance.ECommerceSolutions;
				}
				set
				{
					mInstance.ECommerceSolutions = value;
				}
			}


			/// <summary>
			/// Ecom Img.
			/// </summary>
			public DocumentAttachment EcomImg
			{
				get
				{
					return mInstance.GetFieldDocumentAttachment("EcomImg");
				}
			}


			/// <summary>
			/// Software Development.
			/// </summary>
			public string SoftwareDevelopment
			{
				get
				{
					return mInstance.SoftwareDevelopment;
				}
				set
				{
					mInstance.SoftwareDevelopment = value;
				}
			}


			/// <summary>
			/// Software Img.
			/// </summary>
			public DocumentAttachment SoftwareImg
			{
				get
				{
					return mInstance.GetFieldDocumentAttachment("SoftwareImg");
				}
			}


			/// <summary>
			/// Hire Developer.
			/// </summary>
			public string HireDeveloper
			{
				get
				{
					return mInstance.HireDeveloper;
				}
				set
				{
					mInstance.HireDeveloper = value;
				}
			}


			/// <summary>
			/// Hire Img.
			/// </summary>
			public DocumentAttachment HireImg
			{
				get
				{
					return mInstance.GetFieldDocumentAttachment("HireImg");
				}
			}
		}

		#endregion


		#region "Constructors"

		/// <summary>
		/// Initializes a new instance of the <see cref="Services" /> class.
		/// </summary>
		public Services() : base(CLASS_NAME)
		{
			mFields = new ServicesFields(this);
		}

		#endregion
	}
}