//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at https://docs.xperience.io/.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using CMS.DocumentEngine;
using CMS.DocumentEngine.Types.Aiminfomatics;

[assembly: RegisterDocumentType(ContactUs.CLASS_NAME, typeof(ContactUs))]

namespace CMS.DocumentEngine.Types.Aiminfomatics
{
	/// <summary>
	/// Represents a content item of type ContactUs.
	/// </summary>
	public partial class ContactUs : TreeNode
	{
		#region "Constants and variables"

		/// <summary>
		/// The name of the data class.
		/// </summary>
		public const string CLASS_NAME = "Aiminfomatics.ContactUs";


		/// <summary>
		/// The instance of the class that provides extended API for working with ContactUs fields.
		/// </summary>
		private readonly ContactUsFields mFields;

		#endregion


		#region "Properties"

		/// <summary>
		/// ContactUsID.
		/// </summary>
		[DatabaseIDField]
		public int ContactUsID
		{
			get
			{
				return ValidationHelper.GetInteger(GetValue("ContactUsID"), 0);
			}
			set
			{
				SetValue("ContactUsID", value);
			}
		}


		/// <summary>
		/// Contactus.
		/// </summary>
		[DatabaseField]
		public string ContactName
		{
			get
			{
				return ValidationHelper.GetString(GetValue("ContactName"), @"");
			}
			set
			{
				SetValue("ContactName", value);
			}
		}


		/// <summary>
		/// Satification.
		/// </summary>
		[DatabaseField]
		public string Satification
		{
			get
			{
				return ValidationHelper.GetString(GetValue("Satification"), @"");
			}
			set
			{
				SetValue("Satification", value);
			}
		}


		/// <summary>
		/// ContactFeel.
		/// </summary>
		[DatabaseField]
		public string ContactFeel
		{
			get
			{
				return ValidationHelper.GetString(GetValue("ContactFeel"), @"");
			}
			set
			{
				SetValue("ContactFeel", value);
			}
		}


		/// <summary>
		/// HeadOffice.
		/// </summary>
		[DatabaseField]
		public string HeadOffice
		{
			get
			{
				return ValidationHelper.GetString(GetValue("HeadOffice"), @"");
			}
			set
			{
				SetValue("HeadOffice", value);
			}
		}


		/// <summary>
		/// AimInfomatics.
		/// </summary>
		[DatabaseField]
		public string AimInfomatics
		{
			get
			{
				return ValidationHelper.GetString(GetValue("AimInfomatics"), @"");
			}
			set
			{
				SetValue("AimInfomatics", value);
			}
		}


		/// <summary>
		/// IndiaTxt.
		/// </summary>
		[DatabaseField]
		public string IndiaTxt
		{
			get
			{
				return ValidationHelper.GetString(GetValue("IndiaTxt"), @"");
			}
			set
			{
				SetValue("IndiaTxt", value);
			}
		}


		/// <summary>
		/// USATxt.
		/// </summary>
		[DatabaseField]
		public string USATxt
		{
			get
			{
				return ValidationHelper.GetString(GetValue("USATxt"), @"");
			}
			set
			{
				SetValue("USATxt", value);
			}
		}


		/// <summary>
		/// SalesMailId.
		/// </summary>
		[DatabaseField]
		public string SalesMailId
		{
			get
			{
				return ValidationHelper.GetString(GetValue("SalesMailId"), @"");
			}
			set
			{
				SetValue("SalesMailId", value);
			}
		}


		/// <summary>
		/// MailText.
		/// </summary>
		[DatabaseField]
		public string MailText
		{
			get
			{
				return ValidationHelper.GetString(GetValue("MailText"), @"");
			}
			set
			{
				SetValue("MailText", value);
			}
		}


		/// <summary>
		/// MailClickText.
		/// </summary>
		[DatabaseField]
		public string MailClickText
		{
			get
			{
				return ValidationHelper.GetString(GetValue("MailClickText"), @"");
			}
			set
			{
				SetValue("MailClickText", value);
			}
		}


		/// <summary>
		/// WebsiteUrl.
		/// </summary>
		[DatabaseField]
		public string WebsiteUrl
		{
			get
			{
				return ValidationHelper.GetString(GetValue("WebsiteUrl"), @"");
			}
			set
			{
				SetValue("WebsiteUrl", value);
			}
		}


		/// <summary>
		/// WebsiteUrlClick.
		/// </summary>
		[DatabaseField]
		public string WebsiteUrlClick
		{
			get
			{
				return ValidationHelper.GetString(GetValue("WebsiteUrlClick"), @"");
			}
			set
			{
				SetValue("WebsiteUrlClick", value);
			}
		}


		/// <summary>
		/// WebsiteTxt.
		/// </summary>
		[DatabaseField]
		public string WebsiteTxt
		{
			get
			{
				return ValidationHelper.GetString(GetValue("WebsiteTxt"), @"");
			}
			set
			{
				SetValue("WebsiteTxt", value);
			}
		}


		/// <summary>
		/// Gets an object that provides extended API for working with ContactUs fields.
		/// </summary>
		[RegisterProperty]
		public ContactUsFields Fields
		{
			get
			{
				return mFields;
			}
		}


		/// <summary>
		/// Provides extended API for working with ContactUs fields.
		/// </summary>
		[RegisterAllProperties]
		public partial class ContactUsFields : AbstractHierarchicalObject<ContactUsFields>
		{
			/// <summary>
			/// The content item of type ContactUs that is a target of the extended API.
			/// </summary>
			private readonly ContactUs mInstance;


			/// <summary>
			/// Initializes a new instance of the <see cref="ContactUsFields" /> class with the specified content item of type ContactUs.
			/// </summary>
			/// <param name="instance">The content item of type ContactUs that is a target of the extended API.</param>
			public ContactUsFields(ContactUs instance)
			{
				mInstance = instance;
			}


			/// <summary>
			/// ContactUsID.
			/// </summary>
			public int ID
			{
				get
				{
					return mInstance.ContactUsID;
				}
				set
				{
					mInstance.ContactUsID = value;
				}
			}


			/// <summary>
			/// Contactus.
			/// </summary>
			public string ContactName
			{
				get
				{
					return mInstance.ContactName;
				}
				set
				{
					mInstance.ContactName = value;
				}
			}


			/// <summary>
			/// Satification.
			/// </summary>
			public string Satification
			{
				get
				{
					return mInstance.Satification;
				}
				set
				{
					mInstance.Satification = value;
				}
			}


			/// <summary>
			/// ContactFeel.
			/// </summary>
			public string ContactFeel
			{
				get
				{
					return mInstance.ContactFeel;
				}
				set
				{
					mInstance.ContactFeel = value;
				}
			}


			/// <summary>
			/// HeadOffice.
			/// </summary>
			public string HeadOffice
			{
				get
				{
					return mInstance.HeadOffice;
				}
				set
				{
					mInstance.HeadOffice = value;
				}
			}


			/// <summary>
			/// AimInfomatics.
			/// </summary>
			public string AimInfomatics
			{
				get
				{
					return mInstance.AimInfomatics;
				}
				set
				{
					mInstance.AimInfomatics = value;
				}
			}


			/// <summary>
			/// IndiaTxt.
			/// </summary>
			public string IndiaTxt
			{
				get
				{
					return mInstance.IndiaTxt;
				}
				set
				{
					mInstance.IndiaTxt = value;
				}
			}


			/// <summary>
			/// USATxt.
			/// </summary>
			public string USATxt
			{
				get
				{
					return mInstance.USATxt;
				}
				set
				{
					mInstance.USATxt = value;
				}
			}


			/// <summary>
			/// SalesMailId.
			/// </summary>
			public string SalesMailId
			{
				get
				{
					return mInstance.SalesMailId;
				}
				set
				{
					mInstance.SalesMailId = value;
				}
			}


			/// <summary>
			/// MailText.
			/// </summary>
			public string MailText
			{
				get
				{
					return mInstance.MailText;
				}
				set
				{
					mInstance.MailText = value;
				}
			}


			/// <summary>
			/// MailClickText.
			/// </summary>
			public string MailClickText
			{
				get
				{
					return mInstance.MailClickText;
				}
				set
				{
					mInstance.MailClickText = value;
				}
			}


			/// <summary>
			/// WebsiteUrl.
			/// </summary>
			public string WebsiteUrl
			{
				get
				{
					return mInstance.WebsiteUrl;
				}
				set
				{
					mInstance.WebsiteUrl = value;
				}
			}


			/// <summary>
			/// WebsiteUrlClick.
			/// </summary>
			public string WebsiteUrlClick
			{
				get
				{
					return mInstance.WebsiteUrlClick;
				}
				set
				{
					mInstance.WebsiteUrlClick = value;
				}
			}


			/// <summary>
			/// WebsiteTxt.
			/// </summary>
			public string WebsiteTxt
			{
				get
				{
					return mInstance.WebsiteTxt;
				}
				set
				{
					mInstance.WebsiteTxt = value;
				}
			}
		}

		#endregion


		#region "Constructors"

		/// <summary>
		/// Initializes a new instance of the <see cref="ContactUs" /> class.
		/// </summary>
		public ContactUs() : base(CLASS_NAME)
		{
			mFields = new ContactUsFields(this);
		}

		#endregion
	}
}