//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at https://docs.xperience.io/.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using CMS.DocumentEngine;
using CMS.DocumentEngine.Types.Aiminfomatics;

[assembly: RegisterDocumentType(SocialLink.CLASS_NAME, typeof(SocialLink))]

namespace CMS.DocumentEngine.Types.Aiminfomatics
{
	/// <summary>
	/// Represents a content item of type SocialLink.
	/// </summary>
	public partial class SocialLink : TreeNode
	{
		#region "Constants and variables"

		/// <summary>
		/// The name of the data class.
		/// </summary>
		public const string CLASS_NAME = "Aiminfomatics.SocialLink";


		/// <summary>
		/// The instance of the class that provides extended API for working with SocialLink fields.
		/// </summary>
		private readonly SocialLinkFields mFields;

		#endregion


		#region "Properties"

		/// <summary>
		/// SocialLinkID.
		/// </summary>
		[DatabaseIDField]
		public int SocialLinkID
		{
			get
			{
				return ValidationHelper.GetInteger(GetValue("SocialLinkID"), 0);
			}
			set
			{
				SetValue("SocialLinkID", value);
			}
		}


		/// <summary>
		/// Get In.
		/// </summary>
		[DatabaseField]
		public string GetIn
		{
			get
			{
				return ValidationHelper.GetString(GetValue("GetIn"), @"");
			}
			set
			{
				SetValue("GetIn", value);
			}
		}


		/// <summary>
		/// Touch.
		/// </summary>
		[DatabaseField]
		public string Touch
		{
			get
			{
				return ValidationHelper.GetString(GetValue("Touch"), @"");
			}
			set
			{
				SetValue("Touch", value);
			}
		}


		/// <summary>
		/// Social.
		/// </summary>
		[DatabaseField]
		public string Social
		{
			get
			{
				return ValidationHelper.GetString(GetValue("Social"), @"");
			}
			set
			{
				SetValue("Social", value);
			}
		}


		/// <summary>
		/// Media.
		/// </summary>
		[DatabaseField]
		public string Media
		{
			get
			{
				return ValidationHelper.GetString(GetValue("Media"), @"");
			}
			set
			{
				SetValue("Media", value);
			}
		}


		/// <summary>
		/// Twitter Img.
		/// </summary>
		[DatabaseField]
		public Guid TwitterImg
		{
			get
			{
				return ValidationHelper.GetGuid(GetValue("TwitterImg"), Guid.Empty);
			}
			set
			{
				SetValue("TwitterImg", value);
			}
		}


		/// <summary>
		/// Twitter Url.
		/// </summary>
		[DatabaseField]
		public string TwitterUrl
		{
			get
			{
				return ValidationHelper.GetString(GetValue("TwitterUrl"), @"");
			}
			set
			{
				SetValue("TwitterUrl", value);
			}
		}


		/// <summary>
		/// Facbook Img.
		/// </summary>
		[DatabaseField]
		public Guid FacbookImg
		{
			get
			{
				return ValidationHelper.GetGuid(GetValue("FacbookImg"), Guid.Empty);
			}
			set
			{
				SetValue("FacbookImg", value);
			}
		}


		/// <summary>
		/// Facbook Url.
		/// </summary>
		[DatabaseField]
		public string FacbookUrl
		{
			get
			{
				return ValidationHelper.GetString(GetValue("FacbookUrl"), @"");
			}
			set
			{
				SetValue("FacbookUrl", value);
			}
		}


		/// <summary>
		/// Bribbble Img.
		/// </summary>
		[DatabaseField]
		public Guid BribbbleImg
		{
			get
			{
				return ValidationHelper.GetGuid(GetValue("BribbbleImg"), Guid.Empty);
			}
			set
			{
				SetValue("BribbbleImg", value);
			}
		}


		/// <summary>
		/// Bribbble Url.
		/// </summary>
		[DatabaseField]
		public string BribbbleUrl
		{
			get
			{
				return ValidationHelper.GetString(GetValue("BribbbleUrl"), @"");
			}
			set
			{
				SetValue("BribbbleUrl", value);
			}
		}


		/// <summary>
		/// Google Img.
		/// </summary>
		[DatabaseField]
		public Guid GoogleImg
		{
			get
			{
				return ValidationHelper.GetGuid(GetValue("GoogleImg"), Guid.Empty);
			}
			set
			{
				SetValue("GoogleImg", value);
			}
		}


		/// <summary>
		/// Google Url.
		/// </summary>
		[DatabaseField]
		public string GoogleUrl
		{
			get
			{
				return ValidationHelper.GetString(GetValue("GoogleUrl"), @"");
			}
			set
			{
				SetValue("GoogleUrl", value);
			}
		}


		/// <summary>
		/// Instagram Img.
		/// </summary>
		[DatabaseField]
		public Guid InstagramImg
		{
			get
			{
				return ValidationHelper.GetGuid(GetValue("InstagramImg"), Guid.Empty);
			}
			set
			{
				SetValue("InstagramImg", value);
			}
		}


		/// <summary>
		/// Instagram Url.
		/// </summary>
		[DatabaseField]
		public string InstagramUrl
		{
			get
			{
				return ValidationHelper.GetString(GetValue("InstagramUrl"), @"");
			}
			set
			{
				SetValue("InstagramUrl", value);
			}
		}


		/// <summary>
		/// Email Img.
		/// </summary>
		[DatabaseField]
		public Guid EmailImg
		{
			get
			{
				return ValidationHelper.GetGuid(GetValue("EmailImg"), Guid.Empty);
			}
			set
			{
				SetValue("EmailImg", value);
			}
		}


		/// <summary>
		/// Email Url.
		/// </summary>
		[DatabaseField]
		public string EmailUrl
		{
			get
			{
				return ValidationHelper.GetString(GetValue("EmailUrl"), @"");
			}
			set
			{
				SetValue("EmailUrl", value);
			}
		}


		/// <summary>
		/// Email Txt.
		/// </summary>
		[DatabaseField]
		public string EmailTxt
		{
			get
			{
				return ValidationHelper.GetString(GetValue("EmailTxt"), @"");
			}
			set
			{
				SetValue("EmailTxt", value);
			}
		}


		/// <summary>
		/// Email Id Txt.
		/// </summary>
		[DatabaseField]
		public string EmailIdTxt
		{
			get
			{
				return ValidationHelper.GetString(GetValue("EmailIdTxt"), @"");
			}
			set
			{
				SetValue("EmailIdTxt", value);
			}
		}


		/// <summary>
		/// Phone Txt.
		/// </summary>
		[DatabaseField]
		public string PhoneTxt
		{
			get
			{
				return ValidationHelper.GetString(GetValue("PhoneTxt"), @"");
			}
			set
			{
				SetValue("PhoneTxt", value);
			}
		}


		/// <summary>
		/// PhoneNo.
		/// </summary>
		[DatabaseField]
		public string PhoneNo
		{
			get
			{
				return ValidationHelper.GetString(GetValue("PhoneNo"), @"");
			}
			set
			{
				SetValue("PhoneNo", value);
			}
		}


		/// <summary>
		/// Address.
		/// </summary>
		[DatabaseField]
		public string Address
		{
			get
			{
				return ValidationHelper.GetString(GetValue("Address"), @"");
			}
			set
			{
				SetValue("Address", value);
			}
		}


		/// <summary>
		/// Gets an object that provides extended API for working with SocialLink fields.
		/// </summary>
		[RegisterProperty]
		public SocialLinkFields Fields
		{
			get
			{
				return mFields;
			}
		}


		/// <summary>
		/// Provides extended API for working with SocialLink fields.
		/// </summary>
		[RegisterAllProperties]
		public partial class SocialLinkFields : AbstractHierarchicalObject<SocialLinkFields>
		{
			/// <summary>
			/// The content item of type SocialLink that is a target of the extended API.
			/// </summary>
			private readonly SocialLink mInstance;


			/// <summary>
			/// Initializes a new instance of the <see cref="SocialLinkFields" /> class with the specified content item of type SocialLink.
			/// </summary>
			/// <param name="instance">The content item of type SocialLink that is a target of the extended API.</param>
			public SocialLinkFields(SocialLink instance)
			{
				mInstance = instance;
			}


			/// <summary>
			/// SocialLinkID.
			/// </summary>
			public int ID
			{
				get
				{
					return mInstance.SocialLinkID;
				}
				set
				{
					mInstance.SocialLinkID = value;
				}
			}


			/// <summary>
			/// Get In.
			/// </summary>
			public string GetIn
			{
				get
				{
					return mInstance.GetIn;
				}
				set
				{
					mInstance.GetIn = value;
				}
			}


			/// <summary>
			/// Touch.
			/// </summary>
			public string Touch
			{
				get
				{
					return mInstance.Touch;
				}
				set
				{
					mInstance.Touch = value;
				}
			}


			/// <summary>
			/// Social.
			/// </summary>
			public string Social
			{
				get
				{
					return mInstance.Social;
				}
				set
				{
					mInstance.Social = value;
				}
			}


			/// <summary>
			/// Media.
			/// </summary>
			public string Media
			{
				get
				{
					return mInstance.Media;
				}
				set
				{
					mInstance.Media = value;
				}
			}


			/// <summary>
			/// Twitter Img.
			/// </summary>
			public DocumentAttachment TwitterImg
			{
				get
				{
					return mInstance.GetFieldDocumentAttachment("TwitterImg");
				}
			}


			/// <summary>
			/// Twitter Url.
			/// </summary>
			public string TwitterUrl
			{
				get
				{
					return mInstance.TwitterUrl;
				}
				set
				{
					mInstance.TwitterUrl = value;
				}
			}


			/// <summary>
			/// Facbook Img.
			/// </summary>
			public DocumentAttachment FacbookImg
			{
				get
				{
					return mInstance.GetFieldDocumentAttachment("FacbookImg");
				}
			}


			/// <summary>
			/// Facbook Url.
			/// </summary>
			public string FacbookUrl
			{
				get
				{
					return mInstance.FacbookUrl;
				}
				set
				{
					mInstance.FacbookUrl = value;
				}
			}


			/// <summary>
			/// Bribbble Img.
			/// </summary>
			public DocumentAttachment BribbbleImg
			{
				get
				{
					return mInstance.GetFieldDocumentAttachment("BribbbleImg");
				}
			}


			/// <summary>
			/// Bribbble Url.
			/// </summary>
			public string BribbbleUrl
			{
				get
				{
					return mInstance.BribbbleUrl;
				}
				set
				{
					mInstance.BribbbleUrl = value;
				}
			}


			/// <summary>
			/// Google Img.
			/// </summary>
			public DocumentAttachment GoogleImg
			{
				get
				{
					return mInstance.GetFieldDocumentAttachment("GoogleImg");
				}
			}


			/// <summary>
			/// Google Url.
			/// </summary>
			public string GoogleUrl
			{
				get
				{
					return mInstance.GoogleUrl;
				}
				set
				{
					mInstance.GoogleUrl = value;
				}
			}


			/// <summary>
			/// Instagram Img.
			/// </summary>
			public DocumentAttachment InstagramImg
			{
				get
				{
					return mInstance.GetFieldDocumentAttachment("InstagramImg");
				}
			}


			/// <summary>
			/// Instagram Url.
			/// </summary>
			public string InstagramUrl
			{
				get
				{
					return mInstance.InstagramUrl;
				}
				set
				{
					mInstance.InstagramUrl = value;
				}
			}


			/// <summary>
			/// Email Img.
			/// </summary>
			public DocumentAttachment EmailImg
			{
				get
				{
					return mInstance.GetFieldDocumentAttachment("EmailImg");
				}
			}


			/// <summary>
			/// Email Url.
			/// </summary>
			public string EmailUrl
			{
				get
				{
					return mInstance.EmailUrl;
				}
				set
				{
					mInstance.EmailUrl = value;
				}
			}


			/// <summary>
			/// Email Txt.
			/// </summary>
			public string EmailTxt
			{
				get
				{
					return mInstance.EmailTxt;
				}
				set
				{
					mInstance.EmailTxt = value;
				}
			}


			/// <summary>
			/// Email Id Txt.
			/// </summary>
			public string EmailIdTxt
			{
				get
				{
					return mInstance.EmailIdTxt;
				}
				set
				{
					mInstance.EmailIdTxt = value;
				}
			}


			/// <summary>
			/// Phone Txt.
			/// </summary>
			public string PhoneTxt
			{
				get
				{
					return mInstance.PhoneTxt;
				}
				set
				{
					mInstance.PhoneTxt = value;
				}
			}


			/// <summary>
			/// PhoneNo.
			/// </summary>
			public string PhoneNo
			{
				get
				{
					return mInstance.PhoneNo;
				}
				set
				{
					mInstance.PhoneNo = value;
				}
			}


			/// <summary>
			/// Address.
			/// </summary>
			public string Address
			{
				get
				{
					return mInstance.Address;
				}
				set
				{
					mInstance.Address = value;
				}
			}
		}

		#endregion


		#region "Constructors"

		/// <summary>
		/// Initializes a new instance of the <see cref="SocialLink" /> class.
		/// </summary>
		public SocialLink() : base(CLASS_NAME)
		{
			mFields = new SocialLinkFields(this);
		}

		#endregion
	}
}