//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at https://docs.xperience.io/.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using CMS.DocumentEngine;
using CMS.DocumentEngine.Types.Aiminfomatics;

[assembly: RegisterDocumentType(Home.CLASS_NAME, typeof(Home))]

namespace CMS.DocumentEngine.Types.Aiminfomatics
{
	/// <summary>
	/// Represents a content item of type Home.
	/// </summary>
	public partial class Home : TreeNode
	{
		#region "Constants and variables"

		/// <summary>
		/// The name of the data class.
		/// </summary>
		public const string CLASS_NAME = "Aiminfomatics.Home";


		/// <summary>
		/// The instance of the class that provides extended API for working with Home fields.
		/// </summary>
		private readonly HomeFields mFields;

		#endregion


		#region "Properties"

		/// <summary>
		/// HomeID.
		/// </summary>
		[DatabaseIDField]
		public int HomeID
		{
			get
			{
				return ValidationHelper.GetInteger(GetValue("HomeID"), 0);
			}
			set
			{
				SetValue("HomeID", value);
			}
		}


		/// <summary>
		/// Graphic Image.
		/// </summary>
		[DatabaseField]
		public Guid HomeGraphicImage
		{
			get
			{
				return ValidationHelper.GetGuid(GetValue("HomeGraphicImage"), Guid.Empty);
			}
			set
			{
				SetValue("HomeGraphicImage", value);
			}
		}


		/// <summary>
		/// Graphic Image1.
		/// </summary>
		[DatabaseField]
		public Guid HomeGraphicIma1ge
		{
			get
			{
				return ValidationHelper.GetGuid(GetValue("HomeGraphicIma1ge"), Guid.Empty);
			}
			set
			{
				SetValue("HomeGraphicIma1ge", value);
			}
		}


		/// <summary>
		/// BG Img.
		/// </summary>
		[DatabaseField]
		public Guid HomeBGImg
		{
			get
			{
				return ValidationHelper.GetGuid(GetValue("HomeBGImg"), Guid.Empty);
			}
			set
			{
				SetValue("HomeBGImg", value);
			}
		}


		/// <summary>
		/// Inspirin.
		/// </summary>
		[DatabaseField]
		public string HomeInspirin
		{
			get
			{
				return ValidationHelper.GetString(GetValue("HomeInspirin"), @"");
			}
			set
			{
				SetValue("HomeInspirin", value);
			}
		}


		/// <summary>
		/// Graphic Text.
		/// </summary>
		[DatabaseField]
		public string HomeGraphicText
		{
			get
			{
				return ValidationHelper.GetString(GetValue("HomeGraphicText"), @"");
			}
			set
			{
				SetValue("HomeGraphicText", value);
			}
		}


		/// <summary>
		/// Read More.
		/// </summary>
		[DatabaseField]
		public string ReadMore
		{
			get
			{
				return ValidationHelper.GetString(GetValue("ReadMore"), @"");
			}
			set
			{
				SetValue("ReadMore", value);
			}
		}


		/// <summary>
		/// Responsive Text.
		/// </summary>
		[DatabaseField]
		public string ResponsiveText
		{
			get
			{
				return ValidationHelper.GetString(GetValue("ResponsiveText"), @"");
			}
			set
			{
				SetValue("ResponsiveText", value);
			}
		}


		/// <summary>
		/// Responsive Text1 .
		/// </summary>
		[DatabaseField]
		public string ResponsiveText1
		{
			get
			{
				return ValidationHelper.GetString(GetValue("ResponsiveText1"), @"");
			}
			set
			{
				SetValue("ResponsiveText1", value);
			}
		}


		/// <summary>
		/// Tech Image.
		/// </summary>
		[DatabaseField]
		public Guid TechImage
		{
			get
			{
				return ValidationHelper.GetGuid(GetValue("TechImage"), Guid.Empty);
			}
			set
			{
				SetValue("TechImage", value);
			}
		}


		/// <summary>
		/// Technology Text.
		/// </summary>
		[DatabaseField]
		public string TechnologyText
		{
			get
			{
				return ValidationHelper.GetString(GetValue("TechnologyText"), @"");
			}
			set
			{
				SetValue("TechnologyText", value);
			}
		}


		/// <summary>
		/// ResponsiveImg.
		/// </summary>
		[DatabaseField]
		public Guid ResponsiveImg
		{
			get
			{
				return ValidationHelper.GetGuid(GetValue("ResponsiveImg"), Guid.Empty);
			}
			set
			{
				SetValue("ResponsiveImg", value);
			}
		}


		/// <summary>
		/// Responsive Content Txt.
		/// </summary>
		[DatabaseField]
		public string ResponsiveContentTxt
		{
			get
			{
				return ValidationHelper.GetString(GetValue("ResponsiveContentTxt"), @"");
			}
			set
			{
				SetValue("ResponsiveContentTxt", value);
			}
		}


		/// <summary>
		/// Support Img.
		/// </summary>
		[DatabaseField]
		public Guid SupportImg
		{
			get
			{
				return ValidationHelper.GetGuid(GetValue("SupportImg"), Guid.Empty);
			}
			set
			{
				SetValue("SupportImg", value);
			}
		}


		/// <summary>
		/// Support Text.
		/// </summary>
		[DatabaseField]
		public string SupportText
		{
			get
			{
				return ValidationHelper.GetString(GetValue("SupportText"), @"");
			}
			set
			{
				SetValue("SupportText", value);
			}
		}


		/// <summary>
		/// World Img.
		/// </summary>
		[DatabaseField]
		public Guid WorldImg
		{
			get
			{
				return ValidationHelper.GetGuid(GetValue("WorldImg"), Guid.Empty);
			}
			set
			{
				SetValue("WorldImg", value);
			}
		}


		/// <summary>
		/// World Text.
		/// </summary>
		[DatabaseField]
		public string WorldText
		{
			get
			{
				return ValidationHelper.GetString(GetValue("WorldText"), @"");
			}
			set
			{
				SetValue("WorldText", value);
			}
		}


		/// <summary>
		/// Color_pc Img.
		/// </summary>
		[DatabaseField]
		public Guid Color_pcImg
		{
			get
			{
				return ValidationHelper.GetGuid(GetValue("Color_pcImg"), Guid.Empty);
			}
			set
			{
				SetValue("Color_pcImg", value);
			}
		}


		/// <summary>
		/// Evole Text.
		/// </summary>
		[DatabaseField]
		public string EvoleText
		{
			get
			{
				return ValidationHelper.GetString(GetValue("EvoleText"), @"");
			}
			set
			{
				SetValue("EvoleText", value);
			}
		}


		/// <summary>
		/// Twitter Txt.
		/// </summary>
		[DatabaseField]
		public string TwitterTxt
		{
			get
			{
				return ValidationHelper.GetString(GetValue("TwitterTxt"), @"");
			}
			set
			{
				SetValue("TwitterTxt", value);
			}
		}


		/// <summary>
		/// Tw Arow Img.
		/// </summary>
		[DatabaseField]
		public Guid TwArowImg
		{
			get
			{
				return ValidationHelper.GetGuid(GetValue("TwArowImg"), Guid.Empty);
			}
			set
			{
				SetValue("TwArowImg", value);
			}
		}


		/// <summary>
		/// Gets an object that provides extended API for working with Home fields.
		/// </summary>
		[RegisterProperty]
		public HomeFields Fields
		{
			get
			{
				return mFields;
			}
		}


		/// <summary>
		/// Provides extended API for working with Home fields.
		/// </summary>
		[RegisterAllProperties]
		public partial class HomeFields : AbstractHierarchicalObject<HomeFields>
		{
			/// <summary>
			/// The content item of type Home that is a target of the extended API.
			/// </summary>
			private readonly Home mInstance;


			/// <summary>
			/// Initializes a new instance of the <see cref="HomeFields" /> class with the specified content item of type Home.
			/// </summary>
			/// <param name="instance">The content item of type Home that is a target of the extended API.</param>
			public HomeFields(Home instance)
			{
				mInstance = instance;
			}


			/// <summary>
			/// HomeID.
			/// </summary>
			public int ID
			{
				get
				{
					return mInstance.HomeID;
				}
				set
				{
					mInstance.HomeID = value;
				}
			}


			/// <summary>
			/// Graphic Image.
			/// </summary>
			public DocumentAttachment GraphicImage
			{
				get
				{
					return mInstance.GetFieldDocumentAttachment("HomeGraphicImage");
				}
			}


			/// <summary>
			/// Graphic Image1.
			/// </summary>
			public DocumentAttachment GraphicIma1ge
			{
				get
				{
					return mInstance.GetFieldDocumentAttachment("HomeGraphicIma1ge");
				}
			}


			/// <summary>
			/// BG Img.
			/// </summary>
			public DocumentAttachment BGImg
			{
				get
				{
					return mInstance.GetFieldDocumentAttachment("HomeBGImg");
				}
			}


			/// <summary>
			/// Inspirin.
			/// </summary>
			public string Inspirin
			{
				get
				{
					return mInstance.HomeInspirin;
				}
				set
				{
					mInstance.HomeInspirin = value;
				}
			}


			/// <summary>
			/// Graphic Text.
			/// </summary>
			public string GraphicText
			{
				get
				{
					return mInstance.HomeGraphicText;
				}
				set
				{
					mInstance.HomeGraphicText = value;
				}
			}


			/// <summary>
			/// Read More.
			/// </summary>
			public string ReadMore
			{
				get
				{
					return mInstance.ReadMore;
				}
				set
				{
					mInstance.ReadMore = value;
				}
			}


			/// <summary>
			/// Responsive Text.
			/// </summary>
			public string ResponsiveText
			{
				get
				{
					return mInstance.ResponsiveText;
				}
				set
				{
					mInstance.ResponsiveText = value;
				}
			}


			/// <summary>
			/// Responsive Text1 .
			/// </summary>
			public string ResponsiveText1
			{
				get
				{
					return mInstance.ResponsiveText1;
				}
				set
				{
					mInstance.ResponsiveText1 = value;
				}
			}


			/// <summary>
			/// Tech Image.
			/// </summary>
			public DocumentAttachment TechImage
			{
				get
				{
					return mInstance.GetFieldDocumentAttachment("TechImage");
				}
			}


			/// <summary>
			/// Technology Text.
			/// </summary>
			public string TechnologyText
			{
				get
				{
					return mInstance.TechnologyText;
				}
				set
				{
					mInstance.TechnologyText = value;
				}
			}


			/// <summary>
			/// ResponsiveImg.
			/// </summary>
			public DocumentAttachment ResponsiveImg
			{
				get
				{
					return mInstance.GetFieldDocumentAttachment("ResponsiveImg");
				}
			}


			/// <summary>
			/// Responsive Content Txt.
			/// </summary>
			public string ResponsiveContentTxt
			{
				get
				{
					return mInstance.ResponsiveContentTxt;
				}
				set
				{
					mInstance.ResponsiveContentTxt = value;
				}
			}


			/// <summary>
			/// Support Img.
			/// </summary>
			public DocumentAttachment SupportImg
			{
				get
				{
					return mInstance.GetFieldDocumentAttachment("SupportImg");
				}
			}


			/// <summary>
			/// Support Text.
			/// </summary>
			public string SupportText
			{
				get
				{
					return mInstance.SupportText;
				}
				set
				{
					mInstance.SupportText = value;
				}
			}


			/// <summary>
			/// World Img.
			/// </summary>
			public DocumentAttachment WorldImg
			{
				get
				{
					return mInstance.GetFieldDocumentAttachment("WorldImg");
				}
			}


			/// <summary>
			/// World Text.
			/// </summary>
			public string WorldText
			{
				get
				{
					return mInstance.WorldText;
				}
				set
				{
					mInstance.WorldText = value;
				}
			}


			/// <summary>
			/// Color_pc Img.
			/// </summary>
			public DocumentAttachment Color_pcImg
			{
				get
				{
					return mInstance.GetFieldDocumentAttachment("Color_pcImg");
				}
			}


			/// <summary>
			/// Evole Text.
			/// </summary>
			public string EvoleText
			{
				get
				{
					return mInstance.EvoleText;
				}
				set
				{
					mInstance.EvoleText = value;
				}
			}


			/// <summary>
			/// Twitter Txt.
			/// </summary>
			public string TwitterTxt
			{
				get
				{
					return mInstance.TwitterTxt;
				}
				set
				{
					mInstance.TwitterTxt = value;
				}
			}


			/// <summary>
			/// Tw Arow Img.
			/// </summary>
			public DocumentAttachment TwArowImg
			{
				get
				{
					return mInstance.GetFieldDocumentAttachment("TwArowImg");
				}
			}
		}

		#endregion


		#region "Constructors"

		/// <summary>
		/// Initializes a new instance of the <see cref="Home" /> class.
		/// </summary>
		public Home() : base(CLASS_NAME)
		{
			mFields = new HomeFields(this);
		}

		#endregion
	}
}